version: "2"

services:
  # web-database:
  #   image: postgres
  web:
    image: alexcstark/carvis
    # volumes allows us to 'poke' that hole in the container to share a fs
    # /opt/app is the working directory
    command: npm run start:dev 
    volumes:
      - ./:/opt/app
    ports:
      - 8000:8000
